# Generated by Django 5.1.3 on 2024-11-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.CharField(default='something', max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(default='something', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='something', max_length=50),
        ),
    ]
