# Generated by Django 5.1.3 on 2024-11-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipe_recipe_ingredients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_ingredients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooktime',
            field=models.IntegerField(default=0, help_text='in min'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
